name: $(date:yyyyMMdd)$(rev:.r)_$(SourceBranchName)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: release

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '02659a7a-05ba-482f-944a-387b4e747f97'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    name: 'dotnetBuild'
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    name: 'dotnetTest'
    command: 'test'
    projects: '**/*[Tt]ests*/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --collect "Code Coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    name: 'dotnetPublish'
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    name: 'publishBuildArtifacts'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'